spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ['http://localhost:4200']
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - x-requested-with
              - authorization
              - Content-type
              - Authorization
              - credential
              - X-XSRF-TOKEN
      routes:
        - id: servicio-usuarios
          uri: lb://servicio-usuarios
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=2
        - id: servicio-hoteles
          uri: lb://servicio-hoteles
          predicates:
            - Path=/api/hoteles/**
          filters:
            - StripPrefix=2
        - id: servicio-vuelos
          uri: lb://servicio-vuelos
          predicates:
            - Path=/api/vuelos/**
          filters:
            - StripPrefix=2
        - id: servicio-boletos
          uri: lb://servicio-boletos
          predicates:
            - Path=/api/boletos/**
          filters:
            - StripPrefix=2
        - id: servicio-pagos
          uri: lb://servicio-pagos
          predicates:
            - Path=/api/pagos/**
          filters:
            - StripPrefix=2
        - id: servicio-oauth
          uri: lb://servicio-oauth
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2